//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fortune_Teller_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FortuneTellerMVCEntities : DbContext
    {
        //
        private string _schemaName = string.Empty;
            //
        public FortuneTellerMVCEntities()
            : base("name=FortuneTellerMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer<FortuneTellerMVCEntities>(new CreateDatabaseIfNotExists<FortuneTellerMVCEntities>());
            modelBuilder.Entity<FortuneTellerMVCEntities>().ToTable("FortuneTellerMVCEntity", _schemaName);
            base.OnModelCreating(modelBuilder);
            throw new UnintentionalCodeFirstException();

        }
    public DbSet<FortuneTellerMVCEntities> FortuneTellerMVCEntity { get; set; }
        public virtual DbSet<BirthMonth> BirthMonths { get; set; }
        public virtual DbSet<ColorID> ColorIDs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
    }
}
